on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

name: Build Rmd

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
      
      - name: Install RMarkDown
        run: install.packages("rmarkdown", dep = TRUE)
        shell: Rscript {0}

      - name: Build Rmd
        run: -e "rmarkdown::render('flights_nyc13/Yaara_Tal_Flights.Rmd',params=list(args = myarg))"
        shell: Rscript {0}
