on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Build Rmd

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render README
        run: Rscript -e "rmarkdown::render('flights_nyc13/Yaara_Tal_Flights.Rmd', output_format = 'md_document',output_dir='./',output_file='README.md')"
      - name: Commit README.md
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto Commit Update README'
          add: '. --force'
