on:
  pull_request:
    branches:
      - main

name: Build Rmd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: flights_nyc13/Yaara_Tal_Flights.Rmd
